### ISSUE TITLE
Support more than 3 open tabs

### ISSUE THREAD

**Issue by ryscheng** [soycode/dorabella#2]

**Comment by soycode** [comment]
I'm also going to say that "allow closing of tabs" (other than the status tab) is part of this.

**Comment by soycode** [comment]
Tab closing now works - small caveat that currently closing a tab always activates the status tab (since that tab can't be closed so is always safe to activate). I'll switch to "neighbor tab" at some point, and also look into adding a scrollbar or something to support more tabs.

**Comment by soycode** [comment]
Fixed - https://github.com/soycode/dorabella/commit/f03ae93fcae4dfbbbbdb8310b746396457502547
